/// Auto-generated by Deno Win32: Windows.Win32.System.Diagnostics.Ceip.Apis

import * as util from "../../../util.ts";

// Structs

export type BOOL = number;

// Native Libraries

try {
  var libKERNEL32 = Deno.dlopen("KERNEL32", {
    CeipIsOptedIn: {
      parameters: [],
      result: "i32",
    },
  }).symbols;
} catch(e) { /* ignore */ }

// Symbols

export function CeipIsOptedIn(): boolean /* Windows.Win32.Foundation.BOOL */ {
  return util.boolFromFfi(libKERNEL32.CeipIsOptedIn());
}

