/// Auto-generated by Deno Win32: Windows.Win32.Devices.Pwm.Apis

import * as util from "../../util.ts";

// Enums
export type PWM_POLARITY = number;

// Constants
export const GUID_DEVINTERFACE_PWM_CONTROLLER_WSZ = `{60824B4C-EED1-4C9C-B49C-1B961461A819}`;
export const IOCTL_PWM_CONTROLLER_GET_INFO = 262144;
export const IOCTL_PWM_CONTROLLER_GET_ACTUAL_PERIOD = 262148;
export const IOCTL_PWM_CONTROLLER_SET_DESIRED_PERIOD = 294920;
export const IOCTL_PWM_PIN_GET_ACTIVE_DUTY_CYCLE_PERCENTAGE = 262544;
export const IOCTL_PWM_PIN_SET_ACTIVE_DUTY_CYCLE_PERCENTAGE = 295316;
export const IOCTL_PWM_PIN_GET_POLARITY = 262552;
export const IOCTL_PWM_PIN_SET_POLARITY = 295324;
export const IOCTL_PWM_PIN_START = 295331;
export const IOCTL_PWM_PIN_STOP = 295335;
export const IOCTL_PWM_PIN_IS_STARTED = 262568;
export const PWM_IOCTL_ID_CONTROLLER_GET_INFO = 0;
export const PWM_IOCTL_ID_CONTROLLER_GET_ACTUAL_PERIOD = 1;
export const PWM_IOCTL_ID_CONTROLLER_SET_DESIRED_PERIOD = 2;
export const PWM_IOCTL_ID_PIN_GET_ACTIVE_DUTY_CYCLE_PERCENTAGE = 100;
export const PWM_IOCTL_ID_PIN_SET_ACTIVE_DUTY_CYCLE_PERCENTAGE = 101;
export const PWM_IOCTL_ID_PIN_GET_POLARITY = 102;
export const PWM_IOCTL_ID_PIN_SET_POLARITY = 103;
export const PWM_IOCTL_ID_PIN_START = 104;
export const PWM_IOCTL_ID_PIN_STOP = 105;
export const PWM_IOCTL_ID_PIN_IS_STARTED = 106;
export const PWM_ACTIVE_HIGH = 0;
export const PWM_ACTIVE_LOW = 1;

// Structs

/**
 * Windows.Win32.Devices.Pwm.PWM_CONTROLLER_INFO (size: 32)
 */
export interface PWM_CONTROLLER_INFO {
  /** usize */
  Size: bigint | number;
  /** u32 */
  PinCount: number;
  /** u64 */
  MinimumPeriod: bigint | number;
  /** u64 */
  MaximumPeriod: bigint | number;
}

export const sizeofPWM_CONTROLLER_INFO = 32;

export function allocPWM_CONTROLLER_INFO(data?: Partial<PWM_CONTROLLER_INFO>): Uint8Array {
  const buf = new Uint8Array(sizeofPWM_CONTROLLER_INFO);
  const view = new DataView(buf.buffer);
  // 0x00: usize
  if (data?.Size !== undefined) view.setBigUint64(0, BigInt(data.Size), true);
  // 0x08: u32
  if (data?.PinCount !== undefined) view.setUint32(8, Number(data.PinCount), true);
  // 0x0c: pad4
  // 0x10: u64
  if (data?.MinimumPeriod !== undefined) view.setBigUint64(16, BigInt(data.MinimumPeriod), true);
  // 0x18: u64
  if (data?.MaximumPeriod !== undefined) view.setBigUint64(24, BigInt(data.MaximumPeriod), true);
  return buf;
}

export class PWM_CONTROLLER_INFOView {
  private readonly view: DataView;
  constructor(private readonly buf: Uint8Array) {
    this.view = new DataView(buf.buffer);
  }

  get buffer(): Uint8Array {
    return this.buf;
  }

  // 0x00: usize
  get Size(): bigint | number {
    return Number(this.view.getBigUint64(0, true));
  }

  // 0x08: u32
  get PinCount(): number {
    return this.view.getUint32(8, true);
  }

  // 0x0c: pad4

  // 0x10: u64
  get MinimumPeriod(): bigint | number {
    return Number(this.view.getBigUint64(16, true));
  }

  // 0x18: u64
  get MaximumPeriod(): bigint | number {
    return Number(this.view.getBigUint64(24, true));
  }

  // 0x00: usize
  set Size(value: bigint | number) {
    this.view.setBigUint64(0, BigInt(value), true);
  }

  // 0x08: u32
  set PinCount(value: number) {
    this.view.setUint32(8, value, true);
  }

  // 0x0c: pad4

  // 0x10: u64
  set MinimumPeriod(value: bigint | number) {
    this.view.setBigUint64(16, BigInt(value), true);
  }

  // 0x18: u64
  set MaximumPeriod(value: bigint | number) {
    this.view.setBigUint64(24, BigInt(value), true);
  }
}

/**
 * Windows.Win32.Devices.Pwm.PWM_CONTROLLER_GET_ACTUAL_PERIOD_OUTPUT (size: 8)
 */
export interface PWM_CONTROLLER_GET_ACTUAL_PERIOD_OUTPUT {
  /** u64 */
  ActualPeriod: bigint | number;
}

export const sizeofPWM_CONTROLLER_GET_ACTUAL_PERIOD_OUTPUT = 8;

export function allocPWM_CONTROLLER_GET_ACTUAL_PERIOD_OUTPUT(data?: Partial<PWM_CONTROLLER_GET_ACTUAL_PERIOD_OUTPUT>): Uint8Array {
  const buf = new Uint8Array(sizeofPWM_CONTROLLER_GET_ACTUAL_PERIOD_OUTPUT);
  const view = new DataView(buf.buffer);
  // 0x00: u64
  if (data?.ActualPeriod !== undefined) view.setBigUint64(0, BigInt(data.ActualPeriod), true);
  return buf;
}

export class PWM_CONTROLLER_GET_ACTUAL_PERIOD_OUTPUTView {
  private readonly view: DataView;
  constructor(private readonly buf: Uint8Array) {
    this.view = new DataView(buf.buffer);
  }

  get buffer(): Uint8Array {
    return this.buf;
  }

  // 0x00: u64
  get ActualPeriod(): bigint | number {
    return Number(this.view.getBigUint64(0, true));
  }

  // 0x00: u64
  set ActualPeriod(value: bigint | number) {
    this.view.setBigUint64(0, BigInt(value), true);
  }
}

/**
 * Windows.Win32.Devices.Pwm.PWM_CONTROLLER_SET_DESIRED_PERIOD_INPUT (size: 8)
 */
export interface PWM_CONTROLLER_SET_DESIRED_PERIOD_INPUT {
  /** u64 */
  DesiredPeriod: bigint | number;
}

export const sizeofPWM_CONTROLLER_SET_DESIRED_PERIOD_INPUT = 8;

export function allocPWM_CONTROLLER_SET_DESIRED_PERIOD_INPUT(data?: Partial<PWM_CONTROLLER_SET_DESIRED_PERIOD_INPUT>): Uint8Array {
  const buf = new Uint8Array(sizeofPWM_CONTROLLER_SET_DESIRED_PERIOD_INPUT);
  const view = new DataView(buf.buffer);
  // 0x00: u64
  if (data?.DesiredPeriod !== undefined) view.setBigUint64(0, BigInt(data.DesiredPeriod), true);
  return buf;
}

export class PWM_CONTROLLER_SET_DESIRED_PERIOD_INPUTView {
  private readonly view: DataView;
  constructor(private readonly buf: Uint8Array) {
    this.view = new DataView(buf.buffer);
  }

  get buffer(): Uint8Array {
    return this.buf;
  }

  // 0x00: u64
  get DesiredPeriod(): bigint | number {
    return Number(this.view.getBigUint64(0, true));
  }

  // 0x00: u64
  set DesiredPeriod(value: bigint | number) {
    this.view.setBigUint64(0, BigInt(value), true);
  }
}

/**
 * Windows.Win32.Devices.Pwm.PWM_CONTROLLER_SET_DESIRED_PERIOD_OUTPUT (size: 8)
 */
export interface PWM_CONTROLLER_SET_DESIRED_PERIOD_OUTPUT {
  /** u64 */
  ActualPeriod: bigint | number;
}

export const sizeofPWM_CONTROLLER_SET_DESIRED_PERIOD_OUTPUT = 8;

export function allocPWM_CONTROLLER_SET_DESIRED_PERIOD_OUTPUT(data?: Partial<PWM_CONTROLLER_SET_DESIRED_PERIOD_OUTPUT>): Uint8Array {
  const buf = new Uint8Array(sizeofPWM_CONTROLLER_SET_DESIRED_PERIOD_OUTPUT);
  const view = new DataView(buf.buffer);
  // 0x00: u64
  if (data?.ActualPeriod !== undefined) view.setBigUint64(0, BigInt(data.ActualPeriod), true);
  return buf;
}

export class PWM_CONTROLLER_SET_DESIRED_PERIOD_OUTPUTView {
  private readonly view: DataView;
  constructor(private readonly buf: Uint8Array) {
    this.view = new DataView(buf.buffer);
  }

  get buffer(): Uint8Array {
    return this.buf;
  }

  // 0x00: u64
  get ActualPeriod(): bigint | number {
    return Number(this.view.getBigUint64(0, true));
  }

  // 0x00: u64
  set ActualPeriod(value: bigint | number) {
    this.view.setBigUint64(0, BigInt(value), true);
  }
}

/**
 * Windows.Win32.Devices.Pwm.PWM_PIN_GET_ACTIVE_DUTY_CYCLE_PERCENTAGE_OUTPUT (size: 8)
 */
export interface PWM_PIN_GET_ACTIVE_DUTY_CYCLE_PERCENTAGE_OUTPUT {
  /** u64 */
  Percentage: bigint | number;
}

export const sizeofPWM_PIN_GET_ACTIVE_DUTY_CYCLE_PERCENTAGE_OUTPUT = 8;

export function allocPWM_PIN_GET_ACTIVE_DUTY_CYCLE_PERCENTAGE_OUTPUT(data?: Partial<PWM_PIN_GET_ACTIVE_DUTY_CYCLE_PERCENTAGE_OUTPUT>): Uint8Array {
  const buf = new Uint8Array(sizeofPWM_PIN_GET_ACTIVE_DUTY_CYCLE_PERCENTAGE_OUTPUT);
  const view = new DataView(buf.buffer);
  // 0x00: u64
  if (data?.Percentage !== undefined) view.setBigUint64(0, BigInt(data.Percentage), true);
  return buf;
}

export class PWM_PIN_GET_ACTIVE_DUTY_CYCLE_PERCENTAGE_OUTPUTView {
  private readonly view: DataView;
  constructor(private readonly buf: Uint8Array) {
    this.view = new DataView(buf.buffer);
  }

  get buffer(): Uint8Array {
    return this.buf;
  }

  // 0x00: u64
  get Percentage(): bigint | number {
    return Number(this.view.getBigUint64(0, true));
  }

  // 0x00: u64
  set Percentage(value: bigint | number) {
    this.view.setBigUint64(0, BigInt(value), true);
  }
}

/**
 * Windows.Win32.Devices.Pwm.PWM_PIN_SET_ACTIVE_DUTY_CYCLE_PERCENTAGE_INPUT (size: 8)
 */
export interface PWM_PIN_SET_ACTIVE_DUTY_CYCLE_PERCENTAGE_INPUT {
  /** u64 */
  Percentage: bigint | number;
}

export const sizeofPWM_PIN_SET_ACTIVE_DUTY_CYCLE_PERCENTAGE_INPUT = 8;

export function allocPWM_PIN_SET_ACTIVE_DUTY_CYCLE_PERCENTAGE_INPUT(data?: Partial<PWM_PIN_SET_ACTIVE_DUTY_CYCLE_PERCENTAGE_INPUT>): Uint8Array {
  const buf = new Uint8Array(sizeofPWM_PIN_SET_ACTIVE_DUTY_CYCLE_PERCENTAGE_INPUT);
  const view = new DataView(buf.buffer);
  // 0x00: u64
  if (data?.Percentage !== undefined) view.setBigUint64(0, BigInt(data.Percentage), true);
  return buf;
}

export class PWM_PIN_SET_ACTIVE_DUTY_CYCLE_PERCENTAGE_INPUTView {
  private readonly view: DataView;
  constructor(private readonly buf: Uint8Array) {
    this.view = new DataView(buf.buffer);
  }

  get buffer(): Uint8Array {
    return this.buf;
  }

  // 0x00: u64
  get Percentage(): bigint | number {
    return Number(this.view.getBigUint64(0, true));
  }

  // 0x00: u64
  set Percentage(value: bigint | number) {
    this.view.setBigUint64(0, BigInt(value), true);
  }
}

/**
 * Windows.Win32.Devices.Pwm.PWM_PIN_GET_POLARITY_OUTPUT (size: 8)
 */
export interface PWM_PIN_GET_POLARITY_OUTPUT {
  /** Windows.Win32.Devices.Pwm.PWM_POLARITY */
  Polarity: PWM_POLARITY;
}

export const sizeofPWM_PIN_GET_POLARITY_OUTPUT = 8;

export function allocPWM_PIN_GET_POLARITY_OUTPUT(data?: Partial<PWM_PIN_GET_POLARITY_OUTPUT>): Uint8Array {
  const buf = new Uint8Array(sizeofPWM_PIN_GET_POLARITY_OUTPUT);
  const view = new DataView(buf.buffer);
  // 0x00: i32
  if (data?.Polarity !== undefined) view.setInt32(0, Number(data.Polarity), true);
  // 0x04: pad4
  return buf;
}

export class PWM_PIN_GET_POLARITY_OUTPUTView {
  private readonly view: DataView;
  constructor(private readonly buf: Uint8Array) {
    this.view = new DataView(buf.buffer);
  }

  get buffer(): Uint8Array {
    return this.buf;
  }

  // 0x00: i32
  get Polarity(): number {
    return this.view.getInt32(0, true);
  }

  // 0x04: pad4

  // 0x00: i32
  set Polarity(value: number) {
    this.view.setInt32(0, value, true);
  }

  // 0x04: pad4
}

/**
 * Windows.Win32.Devices.Pwm.PWM_PIN_SET_POLARITY_INPUT (size: 8)
 */
export interface PWM_PIN_SET_POLARITY_INPUT {
  /** Windows.Win32.Devices.Pwm.PWM_POLARITY */
  Polarity: PWM_POLARITY;
}

export const sizeofPWM_PIN_SET_POLARITY_INPUT = 8;

export function allocPWM_PIN_SET_POLARITY_INPUT(data?: Partial<PWM_PIN_SET_POLARITY_INPUT>): Uint8Array {
  const buf = new Uint8Array(sizeofPWM_PIN_SET_POLARITY_INPUT);
  const view = new DataView(buf.buffer);
  // 0x00: i32
  if (data?.Polarity !== undefined) view.setInt32(0, Number(data.Polarity), true);
  // 0x04: pad4
  return buf;
}

export class PWM_PIN_SET_POLARITY_INPUTView {
  private readonly view: DataView;
  constructor(private readonly buf: Uint8Array) {
    this.view = new DataView(buf.buffer);
  }

  get buffer(): Uint8Array {
    return this.buf;
  }

  // 0x00: i32
  get Polarity(): number {
    return this.view.getInt32(0, true);
  }

  // 0x04: pad4

  // 0x00: i32
  set Polarity(value: number) {
    this.view.setInt32(0, value, true);
  }

  // 0x04: pad4
}

export type BOOLEAN = number;

/**
 * Windows.Win32.Devices.Pwm.PWM_PIN_IS_STARTED_OUTPUT (size: 8)
 */
export interface PWM_PIN_IS_STARTED_OUTPUT {
  /** Windows.Win32.Foundation.BOOLEAN */
  IsStarted: Uint8Array | Deno.PointerValue;
}

export const sizeofPWM_PIN_IS_STARTED_OUTPUT = 8;

export function allocPWM_PIN_IS_STARTED_OUTPUT(data?: Partial<PWM_PIN_IS_STARTED_OUTPUT>): Uint8Array {
  const buf = new Uint8Array(sizeofPWM_PIN_IS_STARTED_OUTPUT);
  const view = new DataView(buf.buffer);
  // 0x00: pointer
  if (data?.IsStarted !== undefined) view.setBigUint64(0, data.IsStarted === null ? 0n : BigInt(Deno.UnsafePointer.value(util.toPointer(data.IsStarted))), true);
  return buf;
}

export class PWM_PIN_IS_STARTED_OUTPUTView {
  private readonly view: DataView;
  constructor(private readonly buf: Uint8Array) {
    this.view = new DataView(buf.buffer);
  }

  get buffer(): Uint8Array {
    return this.buf;
  }

  // 0x00: pointer
  get IsStarted(): Uint8Array | Deno.PointerValue {
    const ptr = this.view.getBigUint64(0, true);
    return Deno.UnsafePointer.create(ptr);
  }

  // 0x00: pointer
  set IsStarted(value: Uint8Array | Deno.PointerValue) {
    this.view.setBigUint64(0, BigInt(Deno.UnsafePointer.value(util.toPointer(value))), true);
  }
}

// Native Libraries

// Symbols

